Consequence 9:

Principal component analysis (PCA) and factor analysis are likely to produce spuri-ous factors and loads.

In [ ]:
3.5

naive empiricism: ebola should not be compared to falls fromladders

In [ ]:
Mediocristan vs. Extremistan:

Claim: 

In [15]:
import numpy as np
import torch
from torch import optim
from tqdm import tqdm

## Mediocristan
* In Mediocristan, the probability of sampling higher than X twice in arow is greater than sampling higher than 2X once.

In [117]:
mu = 4 * torch.ones([2])
sigma = torch.eye(2)
_x = torch.tensor([1.], requires_grad=True)
optimizer = optim.Adam([_x], lr=0.01)

for i in tqdm(range(10000)):
    optimizer.zero_grad()

    x = torch.stack([_x, 15 - _x]).squeeze() # constraint
    px = torch.exp(-0.5 * (x - mu).T @ sigma.inverse() @ (x - mu)) / torch.sqrt((2*np.pi)**2 * sigma.det())  
#     log_px =  -0.5 * (x - mu).T @ sigma.inverse() @ (x - mu) - 0.5 * torch.log((2*np.pi)**2 * sigma.det())
    
    loss = -px
    loss.backward()
    optimizer.step()
    if i % 100 == 0:
#         print(_x.item(), px.item(), log_px.item(), loss.item(), x, langrage_lambda.item())
        pass

print(x) #

100%|██████████| 10000/10000 [00:05<00:00, 1798.54it/s]

tensor([ 1., 14.], grad_fn=<SqueezeBackward0>)


tensor(-1021.8099, grad_fn=<DotBackward>)

(tensor([101.0032], requires_grad=True),
 tensor([1., 9.], grad_fn=<SqueezeBackward0>),
 tensor([101.0032, -91.0032], grad_fn=<CatBackward>))

In [125]:
# Pareto
alpha = torch.Tensor([1.])
x_min = torch.Tensor([0.1])
x = torch.tensor([4.], requires_grad=True)

px = ((alpha - 1) / x_min) * (x / x_min).pow(-alpha)
log_px = torch.log((alpha - 1) / x_min) - alpha * torch.log(x) + alpha * torch.log(x_min)

(tensor([0.], grad_fn=<MulBackward0>), tensor([-inf], grad_fn=<AddBackward0>))

In [17]:
## Extremistan, IID LogNormal

mu = 4 * torch.ones([2])
sigma = torch.eye(2)
x = torch.ones([2], requires_grad=True)

optimizer = optim.Adam([x], lr=0.01)

for i in range(100):
    optimizer.zero_grad()
    
    p_x = torch.exp(-0.5 * (x - mu).T @ sigma.inverse() @ (x - mu)) / torch.sqrt((2*np.pi)**2 * sigma.det())   
    objective = p_x - 100 * (x.sum() - 4) # constraint is the sum of variables
    
    loss = -objective
    loss.backward()
    optimizer.step()

print(x) #

tensor([8.7731e-07, 8.7731e-07], requires_grad=True)


In [8]:
x

tensor([2.0006, 2.0006], requires_grad=True)

In [75]:
torch.Tensor([[4, 0], [0, 4]]).inverse()

tensor([[0.2500, -0.0000],
        [0.0000, 0.2500]])

## Learnings

* This highlights the crisp distinction between the two domains; for the class ofsubexponential distributions, ruin is more likely to come from a single extremeevent than from a series of bad episodes.